### YamlMime:PythonClass
uid: azure.servicebus.exceptions.MessageAlreadySettled
name: MessageAlreadySettled
fullName: azure.servicebus.exceptions.MessageAlreadySettled
module: azure.servicebus.exceptions
inheritances:
- builtins.ValueError
summary: 'Failed to settle the message.


  An attempt was made to complete an operation on a message that has already

  been settled (completed, abandoned, dead-lettered or deferred).'
constructor:
  syntax: 'MessageAlreadySettled(**kwargs: Any)'
methods:
- uid: azure.servicebus.exceptions.MessageAlreadySettled.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.servicebus.exceptions.MessageAlreadySettled.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.servicebus.exceptions.MessageAlreadySettled.args
  name: args
