### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.iot.device.exceptions.CredentialError
  fullName: azure.iot.device.exceptions.CredentialError
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - inheritance:
          - type: builtins.object
          type: builtins.BaseException
        type: builtins.Exception
      type: azure.iot.device.common.chainable_exception.ChainableException
    type: azure.iot.device.exceptions.ClientError
  langs:
  - python
  module: azure.iot.device.exceptions
  name: CredentialError
  summary: Could not connect client using given credentials
  syntax:
    content: CredentialError(message=None, cause=None)
  type: class
  uid: azure.iot.device.exceptions.CredentialError
references: []
