### YamlMime:PythonClass
uid: azure.eventhub.exceptions.EventHubError
name: EventHubError
fullName: azure.eventhub.exceptions.EventHubError
module: azure.eventhub.exceptions
inheritances:
- builtins.Exception
summary: Represents an error occurred in the client.
constructor:
  syntax: 'EventHubError(message: str, details: List[str] | None = None)'
  parameters:
  - name: message
    isRequired: true
  - name: details
    defaultValue: None
variables:
- description: The error message.
  name: message
  types:
  - <xref:str>
- description: The error condition, if available.
  name: error
  types:
  - <xref:str>
- description: 'The error details, if included in the

    service response.'
  name: details
  types:
  - <xref:list>[<xref:str>]
methods:
- uid: azure.eventhub.exceptions.EventHubError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.eventhub.exceptions.EventHubError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.eventhub.exceptions.EventHubError.args
  name: args
