### YamlMime:PythonClass
uid: azure.cosmos.errors.CosmosError
name: CosmosError
fullName: azure.cosmos.errors.CosmosError
module: azure.cosmos.errors
inheritances:
- builtins.Exception
summary: Base class for all Azure Cosmos errors.
constructor:
  syntax: CosmosError()
methods:
- uid: azure.cosmos.errors.CosmosError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.cosmos.errors.CosmosError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.cosmos.errors.CosmosError.args
  name: args
