### YamlMime:PythonClass
uid: azure.mgmt.datamigration.models.ValidationError
name: ValidationError
fullName: azure.mgmt.datamigration.models.ValidationError
module: azure.mgmt.datamigration.models
inheritances:
- azure.mgmt.datamigration._serialization.Model
summary: Description about the errors happen while performing migration validation.
constructor:
  syntax: 'ValidationError(*, text: str | None = None, severity: str | _models.Severity
    | None = None, **kwargs)'
  keywordOnlyParameters:
  - name: text
    description: Error Text.
    types:
    - <xref:str>
  - name: severity
    description: 'Severity of the error. Known values are: "Message", "Warning", and
      "Error".'
    types:
    - <xref:str>
    - <xref:azure.mgmt.datamigration.models.Severity>
variables:
- description: Error Text.
  name: text
  types:
  - <xref:str>
- description: 'Severity of the error. Known values are: "Message", "Warning", and
    "Error".'
  name: severity
  types:
  - <xref:str>
  - <xref:azure.mgmt.datamigration.models.Severity>
