### YamlMime:PythonClass
uid: azure.cosmosdb.table.models.AzureBatchOperationError
name: AzureBatchOperationError
fullName: azure.cosmosdb.table.models.AzureBatchOperationError
module: azure.cosmosdb.table.models
inheritances:
- azure.common.AzureHttpError
summary: Indicates that a batch operation failed.
constructor:
  syntax: AzureBatchOperationError(message, status_code, *args, **kwargs)
  parameters:
  - name: message
    isRequired: true
  - name: status_code
    isRequired: true
  - name: batch_code
    isRequired: true
variables:
- description: 'A detailed error message indicating the index of the batch

    request which failed and the reason for the failure. For example,

    ''0:One of the request inputs is out of range.'' indicates the 0th batch

    request failed as one of its property values was out of range.'
  name: message
  types:
  - <xref:str>
- description: The HTTP status code of the batch request. For example, 400.
  name: status_code
  types:
  - <xref:int>
- description: The batch status code. For example, 'OutOfRangeInput'.
  name: batch_code
  types:
  - <xref:str>
methods:
- uid: azure.cosmosdb.table.models.AzureBatchOperationError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.cosmosdb.table.models.AzureBatchOperationError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.cosmosdb.table.models.AzureBatchOperationError.args
  name: args
