### YamlMime:PythonClass
uid: azure.ai.ml.exceptions.UserErrorException
name: UserErrorException
fullName: azure.ai.ml.exceptions.UserErrorException
module: azure.ai.ml.exceptions
inheritances:
- azure.ai.ml.exceptions.MlException
summary: Exception raised when invalid or unsupported inputs are provided.
constructor:
  syntax: 'UserErrorException(message, no_personal_data_message=None, error_category=''UserError'',
    target: ErrorTarget = ''Pipeline'')'
  parameters:
  - name: message
  - name: no_personal_data_message
    defaultValue: None
  - name: error_category
    defaultValue: UserError
  - name: target
    defaultValue: Pipeline
