### YamlMime:PythonClass
uid: azure.messaging.webpubsubclient.models.SendMessageError
name: SendMessageError
fullName: azure.messaging.webpubsubclient.models.SendMessageError
module: azure.messaging.webpubsubclient.models
inheritances:
- builtins.Exception
constructor:
  syntax: 'SendMessageError(message: str, ack_id: int | None = None, error_detail:
    AckMessageError | None = None)'
  parameters:
  - name: message
    isRequired: true
  - name: ack_id
    defaultValue: None
  - name: error_detail
    defaultValue: None
methods:
- uid: azure.messaging.webpubsubclient.models.SendMessageError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.messaging.webpubsubclient.models.SendMessageError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.messaging.webpubsubclient.models.SendMessageError.args
  name: args
