### YamlMime:UniversalReference
api_name: []
items:
- children:
  - msrestazure.azure_exceptions.CloudError
  - msrestazure.azure_exceptions.CloudErrorData
  - msrestazure.azure_exceptions.CloudErrorRoot
  fullName: msrestazure.azure_exceptions
  langs:
  - python
  module: msrestazure.azure_exceptions
  name: azure_exceptions
  source:
    id: azure_exceptions
    path: msrestazure\azure_exceptions.py
    remote:
      branch: master
      path: msrestazure\azure_exceptions.py
      repo: https://github.com/Azure/msrestazure-for-python.git
    startLine: 0
  type: module
  uid: msrestazure.azure_exceptions
references:
- fullName: msrestazure.azure_exceptions.CloudError
  isExternal: false
  name: CloudError
  parent: msrestazure.azure_exceptions
  uid: msrestazure.azure_exceptions.CloudError
- fullName: msrestazure.azure_exceptions.CloudErrorData
  isExternal: false
  name: CloudErrorData
  parent: msrestazure.azure_exceptions
  uid: msrestazure.azure_exceptions.CloudErrorData
- fullName: msrestazure.azure_exceptions.CloudErrorRoot
  isExternal: false
  name: CloudErrorRoot
  parent: msrestazure.azure_exceptions
  uid: msrestazure.azure_exceptions.CloudErrorRoot
